// File generated by FlutterFire CLI.
// This file contains Firebase configuration for your Flutter app.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbAJP99zcj7ct4k8uO0GN9kFvuCwDlABw',
    appId: '1:538622423250:web:ce0d581d3f23128ff4bd0b',
    messagingSenderId: '538622423250',
    projectId: 'revo-46416',
    authDomain: 'revo-46416.firebaseapp.com',
    storageBucket: 'revo-46416.firebasestorage.app',
    measurementId: 'G-831SC8DCKR',
  );

  // Konfiguration für Web

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEsyoD00t-WC_8REIXyM05T-BfjIjpaxU',
    appId: '1:538622423250:android:a42d6587cc14834ff4bd0b',
    messagingSenderId: '538622423250',
    projectId: 'revo-46416',
    storageBucket: 'revo-46416.firebasestorage.app',
  );

  // Konfiguration für Android

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByr5bq5ulWuFl6PMmBpaRB8imxAVbLOlU',
    appId: '1:538622423250:ios:c9f93df056282c0ef4bd0b',
    messagingSenderId: '538622423250',
    projectId: 'revo-46416',
    storageBucket: 'revo-46416.firebasestorage.app',
    iosBundleId: 'com.example.revo',
  );

  // Konfiguration für iOS

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByr5bq5ulWuFl6PMmBpaRB8imxAVbLOlU',
    appId: '1:538622423250:ios:c9f93df056282c0ef4bd0b',
    messagingSenderId: '538622423250',
    projectId: 'revo-46416',
    storageBucket: 'revo-46416.firebasestorage.app',
    iosBundleId: 'com.example.revo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbAJP99zcj7ct4k8uO0GN9kFvuCwDlABw',
    appId: '1:538622423250:web:9cefbb07e702248cf4bd0b',
    messagingSenderId: '538622423250',
    projectId: 'revo-46416',
    authDomain: 'revo-46416.firebaseapp.com',
    storageBucket: 'revo-46416.firebasestorage.app',
    measurementId: 'G-CP3Q4TG0V0',
  );

}